select = ["E", "F", "B", "W", "ERA", "RET", "UP", "I", "N", "Q"]

ignore = [
    "E501", # Never enforce `E501` (line length violations).
    "E701", # Multiple statements on one line (colon)
    "E741", # Ambiguous variable name: `l`
    "B905", # `zip()` without an explicit `strict=` parameter
]
